### PR TITLE
Keep pymongo at v2

### PR DESCRIPTION
**Pull request by dwinston**
pymatgen-db builders break otherwise.

### CODE REVIEW

**Comment by shyuep** [comment]
Why?

Shyue Ping

**Comment by dwinston** [comment]
Our code uses an interface that was broken in v3. The thing that broke for me was our use of the 'fields' keyword argument to cursor.find, which was removed in v3 (I think it's 'filter' now).

**Comment by wmdrichards** [comment]
The fix is pretty easy -- just don't use the keyword 'fields'; 'fields' and
'filter' are both the second argument.

**Comment by shyuep** [comment]
It’s better to change the MP code to use latest pymongo than to stick to old pymongo. 
The pymongo undergoes substantial improvements with iterations. We are losing those improvements

Shyue Ping

On May 21, 2015 at 09:39:14, Will Richards (notifications@github.com) wrote:

The fix is pretty easy -- just don't use the keyword 'fields'; 'fields' and
'filter' are both the second argument.

**Comment by computron** [comment]
Ok I agree with that, suggest it gets changed back once the fundamnetal
codes are updated. Happy to update FWS as well as it's been on my todo list

**Pull request merged**
