### PR TITLE
Fix activate & deactivate command, correct README.

### PR DESCRIPTION
**Pull request by specter119**
Adapt the changes of master for sjtu branch

### CODE REVIEW

**Comment by montoyjh** [comment]
I'm confused about the way the conditionals are redone, it looks like the codes don't install if the virtualenv folder exists, but the purpose of them originally was to continue an incomplete installation, so you'd want them to install if the virtualenv folder exists.

**Comment by specter119** [comment]
@montoyjh Actually, I also dont' know why the master branch will do this, i just adapt the changes of master branch. What i really what to do is in the next pull, in [01f5150](https://github.com/materialsproject/MPenv/pull/9/commits/01f5150cae6606fb11f237c1300b75cb7103f6c8).

**Comment by tschaume** [comment]
Usually, the user would manually unload the intel module and run `python setup.py develop` if the changes he introduced into one of the code repos require a re-install. As for `mpenv`, I think it's preferable to simply start over with the install of the virtualenv in case of installation problems without the need of re-cloning. It also avoids accidently running `python setup.py develop` in untouched directories that have already been installed successfully. This should instead be in the full purview of the user. It's the better approach for the less experienced user whereas an experienced user can always continue the installation process manually with the `mpenv` code as template if the extra time caused by a full virtualenv reinstall is too long.

I've added more information on the actions to be taken by `mpenv` to the print output: https://github.com/materialsproject/MPenv/commit/5b71bf007d6900fb29362e9f8212e33fb73d6aa5

**Comment by shyuep** [comment]
Honestly, I think MP should just switch to conda as a package and virtual env manager. Conda packages the intel compiler (including the MKL souped up versions of numpy as scipy).
Create a standard set of conda packages and then just do conda install PKG on all your systems and it will run exactly as you believe it should.

Also, conda allows you to create specific environments for sharing.

**Comment by tschaume** [comment]
merged via https://github.com/materialsproject/MPenv/commit/006308bc8a5a587309137ec7f4b235506ded723b

**Comment by shyuep** [comment]
Honestly, I think MP should just switch to conda as a package and virtual
env manager. Conda packages the intel compiler (including the MKL souped up
versions of numpy as scipy).
Create a standard set of conda packages and then just do conda install PKG
on all your systems and it will run exactly as you believe it should.

Shyue Ping

On October 24, 2016 at 4:26:03 PM, Patrick Huck (notifications@github.com)
wrote:

Usually, the user would manually unload the intel module and run python
setup.py develop if the changes he introduced into one of the code repos
require a re-install. As for mpenv, I think it's preferable to simply start
over with the install of the virtualenv in case of installation problems
without the need of re-cloning. It also avoids accidently running python
setup.py develop in untouched directories that have already been installed
successfully. This should instead be in the full purview of the user. It's
the better approach for the less experienced user whereas an experienced
user can always continue the installation process manually with the mpenv
code as template if the extra time caused by a full virtualenv reinstall is
too long.

I've added more information on the actions to be taken by mpenv to the
print output: 5b71bf0
https://github.com/materialsproject/MPenv/commit/5b71bf007d6900fb29362e9f8212e33fb73d6aa5

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/materialsproject/MPenv/pull/9#issuecomment-255894211,
or mute the thread

**Pull request closed without merging**
